### ISSUE TITLE
屬於('影組')?

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/qieyun-js#3]
文檔中有「影組」但代碼中實際並沒有的樣子。。

（沒直接 PR 是因為不太清楚這個「影組」是該加入還是該刪去）

https://github.com/nk2028/qieyun-js/blob/72d064681c8fcb8fb4d4851a9690b5486b2a8360/build/brogue2.js#L1-L9

PS Haskell 式逗號位置好耶～

**Comment by sgalal** [comment]
代碼是幾個月前寫的，而且是用 PureScript 代碼改的，見笑了 (//ω//)

確實有這個問題，那應該加入還是該刪去呢？

**Comment by syimyuzya** [comment]
> 代碼是幾個月前寫的，而且是用 PureScript 代碼改的，見笑了 (//ω//)
> 
> 確實有這個問題，那應該加入還是該刪去呢？

法師娘的看法和文檔一致：「影組」包含影、曉、匣、云四母，不含以母。原因是「見影組」和「幫見影組」都會是很常用的判斷原則。

昨天正是給自造的音系寫推導規則時，發現若干處需要寫 `'見組 或 影曉匣母'`（非三等）／`'見組 或 影曉云母'`（三等）的場合，才發現了這處不一致的。

**Comment by ayaka14732** [comment]
好耶，歡迎 pr，順便改一下版本號

**Comment by sgalal** [comment]
好耶，歡迎 pr，順便改一下版本號
